//
//  FlickrPostsInteractor.swift
//  FlickrPosts
//
//  Created by Anish Kumar on 07/12/19.
//  Copyright (c) 2019 Anish Kumar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FlickrPostsBusinessLogic
{
    func showPosts(request: FlickrPosts.Request)
}

protocol FlickrPostsDataStore
{
    //var name: String { get set }
}

class FlickrPostsInteractor: FlickrPostsBusinessLogic, FlickrPostsDataStore
{
    var presenter: FlickrPostsPresentationLogic?
    var worker: FlickrPostsWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func showPosts(request: FlickrPosts.Request) {
        worker = FlickrPostsWorker()
        worker!.getFlickrPosts(forText: request.text) { (response) in
            self.presenter?.presentPosts(response: response)
        }
    }
}
