//
//  FlickrPostsPresenter.swift
//  FlickrPosts
//
//  Created by Anish Kumar on 07/12/19.
//  Copyright (c) 2019 Anish Kumar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FlickrPostsPresentationLogic
{
    func presentSomething(response: FlickrPosts.Response)
}

class FlickrPostsPresenter: FlickrPostsPresentationLogic
{
    weak var viewController: FlickrPostsDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: FlickrPosts.Response) {
        let viewModel = FlickrPosts.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
