//
//  FlickrPostsPresenter.swift
//  FlickrPosts
//
//  Created by Anish Kumar on 07/12/19.
//  Copyright (c) 2019 Anish Kumar. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FlickrPostsPresentationLogic
{
    func presentPosts(response: FlickrPosts.Response?)
}

class FlickrPostsPresenter: FlickrPostsPresentationLogic
{
    weak var viewController: FlickrPostsDisplayLogic?
    
    // MARK: Do something
    
    func presentPosts(response: FlickrPosts.Response?) {
        let viewModel = FlickrPosts.ViewModel()
        if let response = response {
            for post in response.photos.photo {
                let postVM = FlickrPosts.ViewModel.PostVM(title: post.title, url: post.urlQ, height: post.heightQ, width: post.widthQ)
                viewModel.posts.append(postVM)
            }
        }
        viewController?.displayPosts(viewModel: viewModel)
    }
}
